### ISSUE TITLE
Add option for asking query count

### ISSUE THREAD

**Issue by S2606** [greed2411/twitter-flask-app#1]
@greed2411 Can you provide option for user to ask for query count keeping on mind the limit twitter has restricted on?

**Comment by greed2411** [comment]
Considering the app's popularity it shouldn't be a problem. 

`GET search/tweets | search | 180 | 450` is being mentioned in the page over [here](https://developer.twitter.com/en/docs/basics/rate-limits) that is 180 per user every 15 minutes, otherwise 450 per app for every 15 min. Twitter is generous these days. The `100` in count falls under one API request, not 100 API calls. :D
